### Authenticate
POST {{bookstore-host}}/auth/authenticate
Content-Type: application/json

{
  "username": "POS #001",
  "password": "password"
}

> {%
  if (response.status == 200) {
    client.global.set("accessToken", response.body.accessToken);
  }
%}

### Create a new audit
POST {{bookstore-host}}/audits
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "type": "SUPPLY",
  "entries": [
    {
      "isbn": "0-312-85767-5",
      "quantity": 5
    },
    {
      "isbn": "978-0-7653-2595-2",
      "quantity": 10
    },
    {
      "isbn": "0-312-86459-0",
      "quantity": 15
    }
  ]
}
